### ISSUE TITLE
Práctica 5

### ISSUE THREAD

**Issue by bg55-a** [SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-bg55-a#2]
[Practica 5.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-bg55-a/files/8346987/Practica.5.pdf)

**Comment by JudithReynaCS** [comment]
Calificación:17%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
